### PR TITLE
Validate Composer config in CI

### LINKED ISSUE #1: Validate composer files

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes  #1

### CODE REVIEW

**Comment by LeoColomb** [comment]
Thanks for this PR @szepeviktor!
That said I'm not really sure to understand the goal, as:
* the local `composer.json` is not very important and being strictly validated is useless;
* the `composer.json` files for WordPress releases are now generated through Composer core generator, making sure it is validated. See https://github.com/LeoColomb/wordpress-packager/blob/c7f95d0bd07575a9807b2484173efd529f8db0eb/src/Package/Package.php

**Comment by szepeviktor** [comment]
> is not very important

All right.
For me not very important files are excluded from GitHub :)

**Comment by szepeviktor** [comment]
BTW My goal is to check every byte that is originated from a human.

**Comment by szepeviktor** [comment]
I leave all this up to you!

**Comment by LeoColomb** [comment]
> For me not very important files are excluded from GitHub :)

Ha ha, yeah, ideally! But this one is just an helper, and does not handle concrete data. 🙂 
I'm closing for this one.

**Pull request closed without merging**
